version: "3.7"
services:
  laravel.accounting-visits-server.server:
    image: nginx:alpine
    container_name: laravel.accounting-visits-server.server
    working_dir: /app
    ports:
      - "8180:80"
    volumes:
      - ./:/app
      - ./.dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=accounting-visits-server.loc
    networks:
      - default
      - reverse-proxy

  laravel.accounting-visits-server.fpm:
    image: ruslandev89/php74-fpm-bitrix
    container_name: laravel.accounting-visits-server.fpm
    working_dir: /app
    volumes:
      - .:/app
      - ./.dev/php/php.ini:/etc/php/7.4/fpm/php.ini
      - ./.dev/php/php.ini:/etc/php/7.4/cli/php.ini
    networks:
      - default
      - mysql
      - memcached

networks:
  default:
    name: laravel.accounting-visits-server
  mysql:
    external: true
  memcached:
    external: true
  reverse-proxy:
    external: true
